// <auto-generated />
using System;
using AGV.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGV.Persistence.Migrations
{
    [DbContext(typeof(AgvDbContext))]
    [Migration("20260517124005_AddAreaNode")]
    partial class AddAreaNode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("AGV.Core.Entities.Area", b =>
                {
                    b.Property<int>("AreaRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectiveFromVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxVehicleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("AreaRecordId");

                    b.HasIndex("AreaId", "EffectiveFromVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Area_AreaId_Version");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Location", b =>
                {
                    b.Property<int>("LocationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectiveFromLocationVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationRecordId");

                    b.HasIndex("LocationId", "EffectiveFromLocationVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Location_LocationId_Version");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.LocationAssignment", b =>
                {
                    b.Property<int>("AssignmentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveFromLocationVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuardedAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentRecordId");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_LocationAssignment_LocationId");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_LocationAssignment_NodeId");

                    b.HasIndex("AssignmentId", "EffectiveFromLocationVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_LocationAssignment_Id_Version");

                    b.ToTable("LocationAssignment", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DropoffArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DropoffAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoadType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickupArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PickupAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PickupCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId");

                    b.HasIndex("AssignedVehicleId")
                        .HasDatabaseName("IX_Mission_VehicleId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Mission_OrderId");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Mission_State");

                    b.ToTable("Mission", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Move", b =>
                {
                    b.Property<int>("MoveRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveFromVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxWeightCapacityKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoutingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TravelDirection")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoveRecordId");

                    b.HasIndex("FromNodeId", "ToNodeId")
                        .HasDatabaseName("IX_Move_FromTo");

                    b.HasIndex("MoveId", "EffectiveFromVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Move_MoveId_Version");

                    b.ToTable("Move", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Node", b =>
                {
                    b.Property<int>("NodeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveFromVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte>("NodeType")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeRecordId");

                    b.HasIndex("NodeId", "EffectiveFromVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Node_NodeId_Version");

                    b.ToTable("Node", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityState")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BatteryStateOfCharge")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentMapId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentMissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLoaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastStateReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicle_SerialNumber");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.VehicleFactSheet", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LengthMeters")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("MaxOrderHorizonDepth")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxPayloadKg")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("MaxSpeedMs")
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedActionTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsNurbsTrajectory")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WidthMeters")
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("VehicleId");

                    b.ToTable("VehicleFactSheet", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int?>("RequiredVehicleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ZoneId");

                    b.ToTable("Zone", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.ChargeCycleHistoryRecord", b =>
                {
                    b.Property<long>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BatteryTempAtEnd")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BatteryTempAtStart")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BatteryTempPeak")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ChargeCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChargeStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChargerId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<double?>("EqualizeTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<string>("FaultCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FaultOccurred")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SOCAtEnd")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SOCAtStart")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double?>("SOCDeltaPerHour")
                        .HasColumnType("REAL");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CycleId");

                    b.HasIndex("VehicleId", "ChargeStartedAt")
                        .HasDatabaseName("IX_ChargeCycleHistory_VehicleId_Time");

                    b.ToTable("ChargeCycleHistory", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.ChargeCycleSOCTraceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BatteryTemp")
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("CycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SOC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "Timestamp")
                        .HasDatabaseName("IX_ChargeCycleSOCTrace_CycleId_Time");

                    b.ToTable("ChargeCycleSOCTrace", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.DeadlockHistoryRecord", b =>
                {
                    b.Property<long>("DeadlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EscapeNodeUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvolvedVehicleIds")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGhost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvingVehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeadlockId");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("IX_DeadlockHistory_DetectedAt");

                    b.ToTable("DeadlockHistory", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.FleetPerformanceHourlyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgMissionDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgTravelDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgWaitDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("DeadlocksDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeadlocksResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetourEvents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GhostDeadlocks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionsFaulted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionsSwapped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionsTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderStealingEvents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedirectEvents")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VehicleUtilizationPct")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("UX_FleetPerformanceHourly_Period");

                    b.ToTable("FleetPerformanceHourly", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.ForensicCommandLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("FlushId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MqttTopic")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeSequence")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlushId", "VehicleId", "Timestamp")
                        .HasDatabaseName("IX_ForensicCommandLog_Flush_Vehicle_Time");

                    b.ToTable("ForensicCommandLog", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.ForensicFlushRecord", b =>
                {
                    b.Property<long>("FlushId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandLogCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FlushTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvolvedVehicleIds")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusLogCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrafficLogCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FlushId");

                    b.HasIndex("FlushTimestamp")
                        .HasDatabaseName("IX_ForensicFlush_Timestamp");

                    b.HasIndex("PrimaryVehicleId")
                        .HasDatabaseName("IX_ForensicFlush_VehicleId");

                    b.ToTable("ForensicFlush", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.ForensicStatusLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionStates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveOrderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BatterySOC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<long>("FlushId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HeadingDegrees")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int?>("LastNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("X")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Y")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlushId", "VehicleId", "Timestamp")
                        .HasDatabaseName("IX_ForensicStatusLog_Flush_Vehicle_Time");

                    b.ToTable("ForensicStatusLog", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.ForensicTrafficLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckResults")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContentionWithVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetourEvaluated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetourTaken")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FlushId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItineraryMoveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhaseOutcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourcesChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourcesLocked")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlushId", "VehicleId", "Timestamp")
                        .HasDatabaseName("IX_ForensicTrafficLog_Flush_Vehicle_Time");

                    b.ToTable("ForensicTrafficLog", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.LockContentionHistoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockingVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ContentionResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContentionStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("WaitDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("WaitingVehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WaitingVehicleId", "ContentionStartedAt")
                        .HasDatabaseName("IX_LockContention_VehicleId_Time");

                    b.ToTable("LockContentionHistory", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.MissionHistoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DropArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DropCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DropNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadIdentity")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickupArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickupCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PickupNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSystemRef")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("TransferCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TravelDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WaitDurationSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MissionHistory_CreatedAt");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("IX_MissionHistory_MissionId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_MissionHistory_VehicleId");

                    b.ToTable("MissionHistory", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.MissionStateTransitionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId", "Timestamp")
                        .HasDatabaseName("IX_MissionStateTransition_MissionId_Time");

                    b.ToTable("MissionStateTransition", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.VehicleStatusHistoryDailyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgBatterySOC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ChargeEventsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargeEventsOpportunity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinBatterySOC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("MinutesCharging")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesDriving")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesFaulted")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesIdle")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesOffline")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesWaitingOnLock")
                        .HasColumnType("REAL");

                    b.Property<int>("MissionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "PeriodDate")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleStatusDaily_VehicleId_Period");

                    b.ToTable("VehicleStatusHistoryDaily", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.VehicleStatusHistoryHourlyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgBatterySOC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinBatterySOC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("MinutesCharging")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesDriving")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesFaulted")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesIdle")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesOffline")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesWaitingOnLock")
                        .HasColumnType("REAL");

                    b.Property<int>("MissionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleStatusHourly_VehicleId_Period");

                    b.ToTable("VehicleStatusHistoryHourly", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.VehicleStatusHistoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveMissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityState")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BatteryStateOfCharge")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ErrorState")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HeadingDegrees")
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("IsHeartbeat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatingMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("X")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Y")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "Timestamp")
                        .HasDatabaseName("IX_VehicleStatusHistory_VehicleId_Time");

                    b.ToTable("VehicleStatusHistory", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Data.VehicleUtilizationHourlyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinutesCharging")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesDriving")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesFaulted")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesIdle")
                        .HasColumnType("REAL");

                    b.Property<double>("MinutesWaitingOnLock")
                        .HasColumnType("REAL");

                    b.Property<int>("MissionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("UX_VehicleUtilizationHourly_VehicleId_Period");

                    b.ToTable("VehicleUtilizationHourly", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Entities.AreaNodeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveFromVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_AreaNode_NodeId");

                    b.HasIndex("AreaId", "NodeId", "EffectiveFromVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_AreaNode_Area_Node_Version");

                    b.ToTable("AreaNode", (string)null);
                });

            modelBuilder.Entity("AGV.Persistence.Entities.RoadmapVersionRecord", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("VersionId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_RoadmapVersion_IsActive");

                    b.ToTable("RoadmapVersion", (string)null);
                });

            modelBuilder.Entity("AGV.Core.Entities.Move", b =>
                {
                    b.OwnsOne("AGV.Core.ValueObjects.ClothoidParameters", "Clothoid", b1 =>
                        {
                            b1.Property<int>("MoveRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("ArcLength")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ArcLength");

                            b1.Property<decimal>("EndHeading")
                                .HasColumnType("decimal(8,4)")
                                .HasColumnName("EndHeading");

                            b1.Property<decimal>("ParameterA")
                                .HasColumnType("decimal(12,6)")
                                .HasColumnName("ParameterA");

                            b1.Property<decimal>("StartHeading")
                                .HasColumnType("decimal(8,4)")
                                .HasColumnName("StartHeading");

                            b1.HasKey("MoveRecordId");

                            b1.ToTable("Move");

                            b1.WithOwner()
                                .HasForeignKey("MoveRecordId");
                        });

                    b.OwnsOne("AGV.Core.ValueObjects.SpeedConstraint", "Speed", b1 =>
                        {
                            b1.Property<int>("MoveRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("DefaultSpeed")
                                .HasColumnType("decimal(6,4)")
                                .HasColumnName("DefaultSpeed");

                            b1.Property<decimal>("MaxSpeed")
                                .HasColumnType("decimal(6,4)")
                                .HasColumnName("MaxSpeed");

                            b1.HasKey("MoveRecordId");

                            b1.ToTable("Move");

                            b1.WithOwner()
                                .HasForeignKey("MoveRecordId");
                        });

                    b.Navigation("Clothoid")
                        .IsRequired();

                    b.Navigation("Speed")
                        .IsRequired();
                });

            modelBuilder.Entity("AGV.Core.Entities.Node", b =>
                {
                    b.OwnsOne("AGV.Core.ValueObjects.Coordinate", "Position", b1 =>
                        {
                            b1.Property<int>("NodeRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("X")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("X");

                            b1.Property<decimal>("Y")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Y");

                            b1.Property<decimal>("Z")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(10,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("Z");

                            b1.HasKey("NodeRecordId");

                            b1.ToTable("Node");

                            b1.WithOwner()
                                .HasForeignKey("NodeRecordId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("AGV.Core.Entities.VehicleFactSheet", b =>
                {
                    b.HasOne("AGV.Core.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("AGV.Core.Entities.VehicleFactSheet", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
